import type { Metadata } from "next";
import LayoutPage from "./components/layout/LayoutPage";
import "./globals.css";

// React query
import ReactQueryProvider from "./utils/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Shop | abbas ejlali",
  description: "Generated by Shop | abbas ejlali",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`container max-w-7xl mx-auto  antialiased`}>
        <ReactQueryProvider>
          <LayoutPage>{children}</LayoutPage>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
